[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NODE_OPTIONS = "--experimental-json-modules"

[dev]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[template.environment]
GOOGLE_SERVICE_ACCOUNT = ""
GOOGLE_SHEET_ID = ""
